### ISSUE TITLE
Missing U+0605 ARABIC NUMBER MARK ABOVE for Coptic numbers

### ISSUE THREAD

**Issue by dscorbett** [notofonts/coptic#1]
### Font
NotoSansSymbols2-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansSymbols2-unhinted.zip
Date: 2018-04-03

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
Noto Sans Symbols2 supports the Coptic epact numbers (U+102E0 to U+102FB) but it does not support U+0605 ARABIC NUMBER MARK ABOVE, which is written above any Coptic numbers that follow it.

### Character data
؅𐋪𐋥
U+0605 ARABIC NUMBER MARK ABOVE
U+102EA COPTIC EPACT NUMBER TEN
U+102E5 COPTIC EPACT DIGIT FIVE

**Comment by simoncozens** [comment]
The U+0605 glyph was added some time ago, and there were some commented-out substitutions to make the different widths work. I just uncommented them.

![shape](https://github.com/notofonts/coptic/assets/106728/3ff90825-5011-438b-8f47-458d7daae429)
