### ISSUE TITLE
The appearance of the Middle Dot (U+00B7) should change in Coptic

### ISSUE THREAD

**Issue by pishoyg** [notofonts/coptic#2]
Issue reported by https://github.com/moyogo.

As per [this unicode proposal](https://www.unicode.org/L2/L2010/10348-n3912-coptic-adds.pdf), the middle dot should be placed at cap-height when after a capital letter, at small-cap-height when after a small-cap letter, and at x-height when after a lowercase letter.

**Comment by simoncozens** [comment]
In that proposal, it talks about "the MIDDLE DOT (being at x-height vis-à-vis Greek and Coptic uncial)". It discusses three different marks at three different heights, but I don't see anything about the MIDDLE DOT moving around contextually based on the previous letter. What section should I be looking at?

**Comment by pishoyg** [comment]
My understanding of the statement "at x-height vis-à-vis Greek and Coptic uncial" is that its height should change based on the preceding letter.

**Comment by pishoyg** [comment]
For further context, RAISED DOT U+2E33 should sit between the MIDDLE DOT U+00B7 (at letter height) and FULL STOP U+00E2 (at the baseline).

**Comment by simoncozens** [comment]
My understanding would be that it lives at the font's x-height.

**Comment by moyogo** [comment]
If you look at Brill by @tirotypeworks for example, the MIDDLE DOT has two forms, one for Latin sitting around the x-height median (between baseline and x-height) and one for Greek siting at x-height by default which is shifted to cap-height with the `case` feature and to small-cap-height with the `c2sc` or `smcp` feature.
See for example "Α&lt;case>·&lt;/case> &lt;smcp>α·&lt;/scmp> α·" and "A&lt;case>·&lt;/case> &lt;smcp>a·&lt;/scmp> a·":
<img width="218" alt="Screenshot 2022-08-25 at 06 49 41" src="https://user-images.githubusercontent.com/1923747/186577494-790564c2-d66c-4e1d-ba38-fe1c84f8c04c.png">

Coptic MIDDLE DOT has the same behaviour as the Greek MIDDLE DOT. It could be adjusted contextually or with the case and c2sc/smcp features.

**Comment by simoncozens** [comment]
Added a contextual positioning rule:

![shape](https://github.com/notofonts/coptic/assets/106728/9e125e52-ea16-4c3c-9f42-b857e57e5dec)
