### ISSUE TITLE
Support Coptic Epact Numbers

### ISSUE THREAD

**Issue by pishoyg** [notofonts/coptic#3]
Noto Sans should support the Coptic Epact Numbers: https://www.unicode.org/charts/PDF/U102E0.pdf.

**Comment by simoncozens** [comment]
@pishoyg: Could you please check if this is still an issue on Android (and which version of Android you are using)? The font definitely contains the numbers, and has done for a while, but I wonder if Android has an old version.

**Comment by simoncozens** [comment]
Okay. Android currently has a very old version of this font, unfortunately. But we are currently gathering recommendations for font upgrades for the next version of Android, and I have recommended that the Coptic fonts get updated. I'm afraid it's just a matter of waiting until Android picks up the new versions, as there is no problem with the font.
